jobs:
- job: BuildWindowsWithSonarCloud
  displayName: Build for Windows\MSBuild With SonarCloud
  pool:
    vmImage: 'windows-latest'
  variables:
    BUILD_WRAPPER_DOWNLOAD_URL: https://sonarcloud.io/static/cpp/build-wrapper-win-x86.zip
  steps:
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'SonarCloud' # Name of the SonarCloud service connection you created
      organization: 'sonarsource-cfamily-examples'
      scannerMode: 'CLI'
      configMode: 'file'
      extraProperties: |
        sonar.cfamily.vscoveragexml.reportsPath=$(System.DefaultWorkingDirectory)/CoverageResults/*/*.xml
  - pwsh: |
      curl --create-dirs -sSLo $HOME\.sonar\build-wrapper-win-x86.zip ${{variables.BUILD_WRAPPER_DOWNLOAD_URL}}
      unzip -o $HOME\.sonar\build-wrapper-win-x86.zip -d $HOME\.sonar\
    displayName: Download and install build wrapper
  - pwsh: |
      $path = vswhere -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe | select-object -first 1
      & "$HOME\.sonar\build-wrapper-win-x86\build-wrapper-win-x86-64.exe" --out-dir build_wrapper_output_directory $path sonar_scanner_example.vcxproj /t:rebuild /nodeReuse:false
      & $path test1\test1.vcxproj
      & $path test2\test2.vcxproj
    workingDirectory: .
    displayName: Build in build-wrapper and tests
  - task: VSTest@2
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: |
        test1\*\test1.dll
        test2\*\test2.dll
      searchFolder: '$(System.DefaultWorkingDirectory)'
      resultsFolder: '$(System.DefaultWorkingDirectory)/CoverageResults'
      otherConsoleOptions: '/collect:"Code Coverage;Format=Xml"' # Necessary to have an XML coverage report
      codeCoverageEnabled: true
      testRunTitle: 'Run tests'
  - task: SonarCloudAnalyze@1
